name: "boinkor.net CI/nix - fmt"
description: "Check that all nix files are properly formatted."
author: "Andreas Fuchs <asf@boinkor.net>"
inputs:
  root:
    description: "Directory that the nix flake resides in."
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up nix
      uses: cachix/install-nix-action@v30
    - uses: DeterminateSystems/magic-nix-cache-action@v9
    - name: Check formatting
      run: cd ${{ inputs.root }} && nix fmt
      shell: bash
    - name: Show unformatted files, if any
      shell: bash
      run: git diff --exit-code
      id: result
