name: "boinkor.net CI/nix - fmt"
description: "Check that all nix files are properly formatted."
author: "Andreas Fuchs <asf@boinkor.net>"
inputs:
  root:
    description: "Root directory where the flake.lock file resides"
    default: "."
  extra_nix_config:
    description: "Extra lines to add to nix.conf"
  tailnet_client_id:
    description: "DEPRECATED. Tailnet OAuth Client ID for reaching the nix cache, if necessary."
  tailnet_client_secret:
    description: "DEPRECATED. Tailnet OAuth Client Secret for reaching the nix cache, if necessary."
  tailnet_tags:
    description: "DEPRECATED. Tags to request for the node authenticated by the tailnet oauth client id and secret."
    default: "tag:ci-external"
  attic_cache:
    description: "DEPRECATED. An optional attic nix cache's store name."
  attic_endpoint:
    description: "DEPRECATED. URL where the attic nix cache can be reached."
  attic_token:
    description: "DEPRECATED. Token for authenticating to the attic nix cache."

runs:
  using: "composite"
  steps:
    - uses: canidae-solutions/lix-quick-install-action@v2
      with:
        lix_conf: ${{ inputs.extra_nix_config }}
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles(format('{0}/**/*.nix', inputs.root), format('{0}/**/flake.lock', inputs.root)) }}-${{ github.job }}
        restore-prefixes-first-match: nix-${{ runner.os }}
        gc-max-store-size-linux: 1G
