name: "CI/Nix - builds"
on:
  workflow_call:
    inputs:
      root:
        type: string
        description: "Directory that the nix flake resides in."
        default: "."
      installable:
        type: string
        description: "The derivation to build. That's the part after the # in a flake reference."
        default: ""

jobs:
  flake_build:
    name: "nix build ${{inputs.root}}#${{inputs.installable}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - run: nix build --no-link ${{inputs.root}}#${{inputs.installable}}
