name: "Tests for this repo"
on:
  workflow_call:

jobs:
  success_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/build
        with:
          root: "./tests/success"

  success_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/fmt
        with:
          root: "./tests/success"

  success_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/test
        with:
          root: "./tests/success"

  success_flake_safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/flake_safety
        with:
          root: "./tests/success"

  fail_on_path_inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/flake_safety
        with:
          root: "tests/fail-safety-check"
        id: failure
        continue-on-error: true
      - name: Expect failure
        run: |
          echo "::setFailed::Expected the failure step to fail; instead: ${{steps.failure.outcome}}"
          exit 1
        if: ${{ success() && steps.failure.outcome != 'failure' }}
