name: "Tests for this repo"
on:
  workflow_call:

jobs:
  success_build:
    uses: "./.github/workflows/build.yml"
    with:
      root: "./tests/success"

  success_lint:
    uses: "./.github/workflows/lints.yml"
    with:
      root: "./tests/success"

  success_test:
    uses: "./.github/workflows/tests.yml"
    with:
      root: "./tests/success"

  fail_on_path_inputs:
    uses: "./.github/workflows/_internal_lint_failure.yml"
    with:
      root: "./tests/fail-safety-check"
      failing_job: "flake_safety"
