name: "Tests for this repo"
on:
  workflow_call:

jobs:
  success_build:
    uses: "./.github/workflows/build.yml"
    with:
      root: "./tests/success"

  success_lint:
    uses: "./.github/workflows/lints.yml"
    with:
      root: "./tests/success"

  success_test:
    uses: "./.github/workflows/tests.yml"
    with:
      root: "./tests/success"

  fail_on_path_inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/flake_safety
        with:
          root: "tests/fail-safety-check"
        id: failure
        continue-on-error: true
      - name: Expect failure
        run: |
          echo "::setFailed::Expected the failure step to fail; instead: ${{steps.failure.outcome}}"
          exit 1
        if: ${{ success() && steps.failure.outcome != 'failure' }}
