name: "CI/Nix - formatting"
on:
  workflow_call:
    inputs:
      root:
        type: string
        description: "Directory that the nix flake resides in."
        default: "."

jobs:
  fmt:
    name: "nix fmt ${{inputs.root}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - run: cd ${{ inputs.root }} && nix fmt
      - name: Show unformatted files, if any
        run: git diff --exit-code

  flake_safety:
    name: "nix flake safety"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: inputs with unreproducible lock entries
        run: |
          {
            echo "entries<<EOF"
            nix flake metadata --json | jq -r '.locks.nodes | map_values(select(.locked.type == "path")) | keys[]'
            echo EOF
          } >> "$GITHUB_OUTPUT"
        working-directory: ${{ inputs.root }}
        id: path_nodes
      - name: fail if bad lock entries are present
        if: ${{ steps.path_nodes.outputs.entries != '' }}
        run: |
          echo "The following lock entries are locked as 'path' types, causing the flake to probably be un-usable on machines that don't have that path present:"
          echo "${{steps.path_nodes.outputs.entries}}"
          echo ""
          echo "To remedy, make sure that all of these entries have corresponding inputs in the flake.nix."
          exit 1
