name: "CI/Nix - formatting"
on:
  workflow_call:
    inputs:
      root:
        type: string
        description: "Directory that the nix flake resides in."
        default: "."

jobs:
  fmt:
    name: "nix fmt ${{inputs.root}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - run: cd ${{ inputs.root }} && nix fmt
      - name: Show unformatted files, if any
        run: git diff --exit-code
