name: "CI/Nix - tests"
on:
  workflow_call:
    inputs:
      root:
        type: string
        description: "Directory that the nix flake resides in."
        default: "."
      check_extra_args:
        type: string
        description: "Extra commandline args to pass to `nix flake check`"
        default: ""

jobs:
  flake_check:
    name: "nix flake check ${{inputs.root}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake check -L ${{ inputs.check_extra_args }} ${{ inputs.root }}
