name: "CI/Nix - tests"
on:
  workflow_call:
    inputs:
      root:
        type: string
        description: "Directory that the nix flake resides in."
        default: "."

jobs:
  flake_check:
    name: "nix flake check ${{inputs.root}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake check ${{ inputs.root }}
